[package]
name = "day_23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_helpers = { path = "../aoc_helpers"}
cond_utils = "0.1.0"
itertools = "0.10.5"
simple-matrix = "0.1.2"
